/* The following code was generated by JFlex 1.4.1a on 13/02/12 16:35 */

package fr.uha.ensisa.compil.sound;

import java_cup.runtime.SymbolFactory;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1a
 * on 13/02/12 16:35 from the specification file
 * <tt>fr/uha/ensisa/compil/sound/Lexer.java</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  0,  0,  1,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     1,  0, 29,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0, 29, 29, 29, 
    26, 26, 26, 26, 26, 26, 26, 26, 26, 26,  0,  4,  0,  5,  0,  0, 
     0, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 
    27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,  0,  0,  0,  0, 10, 
     0, 14, 28, 18, 11,  9, 28, 28, 23, 15, 28, 28, 17, 20,  6,  7, 
    21, 25, 13, 24,  8, 12, 16, 22, 28, 19, 28,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\1\1\2\1\3\1\1\1\4\1\5\12\6\1\7"+
    "\1\10\1\3\13\6\1\11\12\6\1\12\1\13\3\6"+
    "\1\14\7\6\1\15\1\16\14\6\1\17\7\6\1\20"+
    "\2\6\1\21\2\6\1\22\1\23";

  private static int [] zzUnpackAction() {
    int [] result = new int[85];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\36\0\74\0\74\0\132\0\74\0\74\0\170"+
    "\0\226\0\264\0\322\0\360\0\u010e\0\u012c\0\u014a\0\u0168"+
    "\0\u0186\0\u01a4\0\226\0\u01c2\0\u01e0\0\u01fe\0\u021c\0\u023a"+
    "\0\u0258\0\u0276\0\u0294\0\u02b2\0\u02d0\0\u02ee\0\u030c\0\226"+
    "\0\u032a\0\u0348\0\u0366\0\u0384\0\u03a2\0\u03c0\0\u03de\0\u03fc"+
    "\0\u041a\0\u0438\0\226\0\u0456\0\u0474\0\u0492\0\u04b0\0\226"+
    "\0\u04ce\0\u04ec\0\u050a\0\u0528\0\u0546\0\u0564\0\u0582\0\226"+
    "\0\226\0\u05a0\0\u05be\0\u05dc\0\u05fa\0\u0618\0\u0636\0\u0654"+
    "\0\u0672\0\u0690\0\u06ae\0\u06cc\0\u06ea\0\226\0\u0708\0\u0726"+
    "\0\u0744\0\u0762\0\u0780\0\u079e\0\u07bc\0\226\0\u07da\0\u07f8"+
    "\0\226\0\u0816\0\u0834\0\226\0\226";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[85];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\5\2\11\1\14\1\11\1\15\1\11\1\16"+
    "\3\11\1\17\1\20\1\11\1\21\1\11\1\22\1\23"+
    "\1\11\1\5\1\3\2\4\1\24\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\5\2\11\1\14\1\11\1\15"+
    "\1\11\1\16\3\11\1\17\1\20\1\11\1\21\1\11"+
    "\1\22\1\23\1\11\1\5\41\0\1\5\2\0\30\5"+
    "\3\0\1\5\2\0\1\11\1\25\25\11\1\5\3\0"+
    "\1\5\2\0\27\11\1\5\3\0\1\5\2\0\11\11"+
    "\1\26\15\11\1\5\3\0\1\5\2\0\1\27\26\11"+
    "\1\5\3\0\1\5\2\0\3\11\1\30\23\11\1\5"+
    "\3\0\1\5\2\0\16\11\1\31\10\11\1\5\3\0"+
    "\1\5\2\0\1\11\1\32\25\11\1\5\3\0\1\5"+
    "\2\0\13\11\1\33\13\11\1\5\3\0\1\5\2\0"+
    "\11\11\1\34\15\11\1\5\3\0\1\5\2\0\3\11"+
    "\1\35\23\11\1\5\3\0\1\5\2\0\24\5\1\22"+
    "\3\5\2\24\1\0\33\24\3\0\1\5\2\0\2\11"+
    "\1\36\24\11\1\5\3\0\1\5\2\0\16\11\1\37"+
    "\10\11\1\5\3\0\1\5\2\0\5\11\1\40\21\11"+
    "\1\5\3\0\1\5\2\0\17\11\1\41\7\11\1\5"+
    "\3\0\1\5\2\0\17\11\1\42\7\11\1\5\3\0"+
    "\1\5\2\0\10\11\1\43\16\11\1\5\3\0\1\5"+
    "\2\0\10\11\1\44\16\11\1\5\3\0\1\5\2\0"+
    "\2\11\1\45\24\11\1\5\3\0\1\5\2\0\23\11"+
    "\1\46\3\11\1\5\3\0\1\5\2\0\3\11\1\47"+
    "\23\11\1\5\3\0\1\5\2\0\3\11\1\50\23\11"+
    "\1\5\3\0\1\5\2\0\3\11\1\51\23\11\1\5"+
    "\3\0\1\5\2\0\1\11\1\52\25\11\1\5\3\0"+
    "\1\5\2\0\5\11\1\53\21\11\1\5\3\0\1\5"+
    "\2\0\15\11\1\54\11\11\1\5\3\0\1\5\2\0"+
    "\21\11\1\55\5\11\1\5\3\0\1\5\2\0\6\11"+
    "\1\56\20\11\1\5\3\0\1\5\2\0\4\11\1\57"+
    "\22\11\1\5\3\0\1\5\2\0\22\11\1\60\4\11"+
    "\1\5\3\0\1\5\2\0\10\11\1\61\16\11\1\5"+
    "\3\0\1\5\2\0\7\11\1\62\17\11\1\5\3\0"+
    "\1\5\2\0\4\11\1\63\22\11\1\5\3\0\1\5"+
    "\2\0\4\11\1\64\22\11\1\5\3\0\1\5\2\0"+
    "\3\11\1\65\23\11\1\5\3\0\1\5\2\0\5\11"+
    "\1\66\4\11\1\67\14\11\1\5\3\0\1\5\2\0"+
    "\2\11\1\70\24\11\1\5\3\0\1\5\2\0\2\11"+
    "\1\71\24\11\1\5\3\0\1\5\2\0\22\11\1\72"+
    "\4\11\1\5\3\0\1\5\2\0\1\73\26\11\1\5"+
    "\3\0\1\5\2\0\1\74\26\11\1\5\3\0\1\5"+
    "\2\0\6\11\1\75\20\11\1\5\3\0\1\5\2\0"+
    "\3\11\1\76\23\11\1\5\3\0\1\5\2\0\11\11"+
    "\1\77\15\11\1\5\3\0\1\5\2\0\1\11\1\100"+
    "\25\11\1\5\3\0\1\5\2\0\14\11\1\101\12\11"+
    "\1\5\3\0\1\5\2\0\7\11\1\102\17\11\1\5"+
    "\3\0\1\5\2\0\13\11\1\103\13\11\1\5\3\0"+
    "\1\5\2\0\16\11\1\104\10\11\1\5\3\0\1\5"+
    "\2\0\2\11\1\105\24\11\1\5\3\0\1\5\2\0"+
    "\3\11\1\106\23\11\1\5\3\0\1\5\2\0\10\11"+
    "\1\107\16\11\1\5\3\0\1\5\2\0\1\11\1\110"+
    "\25\11\1\5\3\0\1\5\2\0\6\11\1\111\20\11"+
    "\1\5\3\0\1\5\2\0\3\11\1\112\23\11\1\5"+
    "\3\0\1\5\2\0\2\11\1\113\24\11\1\5\3\0"+
    "\1\5\2\0\14\11\1\114\12\11\1\5\3\0\1\5"+
    "\2\0\13\11\1\115\13\11\1\5\3\0\1\5\2\0"+
    "\22\11\1\116\4\11\1\5\3\0\1\5\2\0\11\11"+
    "\1\117\15\11\1\5\3\0\1\5\2\0\11\11\1\120"+
    "\15\11\1\5\3\0\1\5\2\0\2\11\1\121\24\11"+
    "\1\5\3\0\1\5\2\0\1\11\1\122\25\11\1\5"+
    "\3\0\1\5\2\0\2\11\1\123\24\11\1\5\3\0"+
    "\1\5\2\0\1\124\26\11\1\5\3\0\1\5\2\0"+
    "\15\11\1\125\11\11\1\5";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2130];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\1\2\11\1\1\2\11\116\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[85];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }
private SymbolFactory symbolFactory;
public SymbolFactory getSymbolFactory() {
	return symbolFactory;
}
public void setSymbolFactory(SymbolFactory symbolFactory) {
	this.symbolFactory = symbolFactory;
}


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      if (zzMarkedPosL > zzStartRead) {
        switch (zzBufferL[zzMarkedPosL-1]) {
        case '\n':
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          zzAtBOL = true;
          break;
        case '\r': 
          if (zzMarkedPosL < zzEndReadL)
            zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          else if (zzAtEOF)
            zzAtBOL = false;
          else {
            boolean eof = zzRefill();
            zzMarkedPosL = zzMarkedPos;
            zzEndReadL = zzEndRead;
            zzBufferL = zzBuffer;
            if (eof) 
              zzAtBOL = false;
            else 
              zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          }
          break;
        default:
          zzAtBOL = false;
        }
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      if (zzAtBOL)
        zzState = ZZ_LEXSTATE[zzLexicalState+1];
      else
        zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 16: 
          { return getSymbolFactory().newSymbol ("WITH_NOTES", Sym.WITH_NOTES);
          }
        case 20: break;
        case 18: 
          { return getSymbolFactory().newSymbol ("NOTE_DURATION", Sym.NOTE_DURATION);
          }
        case 21: break;
        case 4: 
          { return getSymbolFactory().newSymbol ("TERM", Sym.TERM);
          }
        case 22: break;
        case 8: 
          { return getSymbolFactory().newSymbol ("NOTE", Sym.NOTE, new String(yytext()));
          }
        case 23: break;
        case 17: 
          { return getSymbolFactory().newSymbol ("PLAY_SIMULT", Sym.PLAY_SIMULT);
          }
        case 24: break;
        case 10: 
          { return getSymbolFactory().newSymbol ("LOAD", Sym.LOAD);
          }
        case 25: break;
        case 14: 
          { return getSymbolFactory().newSymbol ("IMPORT", Sym.IMPORT);
          }
        case 26: break;
        case 1: 
          { return getSymbolFactory().newSymbol ("STRING", Sym.STRING, new String(yytext()));
          }
        case 27: break;
        case 15: 
          { return getSymbolFactory().newSymbol ("SEQUENCE", Sym.SEQUENCE);
          }
        case 28: break;
        case 6: 
          { return getSymbolFactory().newSymbol ("VARIABLE", Sym.VARIABLE, new String(yytext()));
          }
        case 29: break;
        case 5: 
          { return getSymbolFactory().newSymbol ("EQUAL", Sym.EQUAL);
          }
        case 30: break;
        case 19: 
          { return getSymbolFactory().newSymbol ("NOTE_VELOCITY", Sym.NOTE_VELOCITY);
          }
        case 31: break;
        case 12: 
          { return getSymbolFactory().newSymbol ("TIMES", Sym.TIMES);
          }
        case 32: break;
        case 11: 
          { return getSymbolFactory().newSymbol ("PLAY", Sym.PLAY);
          }
        case 33: break;
        case 13: 
          { return getSymbolFactory().newSymbol ("REPEAT", Sym.REPEAT);
          }
        case 34: break;
        case 2: 
          { throw new Error("Illegal character <"+yytext()+">");
          }
        case 35: break;
        case 7: 
          { return getSymbolFactory().newSymbol ("NUMBER", Sym.NUMBER, new Integer(yytext()));
          }
        case 36: break;
        case 3: 
          { 
          }
        case 37: break;
        case 9: 
          { return getSymbolFactory().newSymbol ("END", Sym.END);
          }
        case 38: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(Sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
