
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 14 01:43:59 CET 2012
//----------------------------------------------------

package fr.uha.ensisa.compil.sound;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int TIMES = 11;
  public static final int IMPORT = 5;
  public static final int SEQUENCE = 9;
  public static final int EQUAL = 3;
  public static final int WITH_NOTES = 8;
  public static final int PLAY = 6;
  public static final int END = 12;
  public static final int VARIABLE = 16;
  public static final int NOTE = 15;
  public static final int PLAY_SIMULT = 7;
  public static final int STRING = 14;
  public static final int NUMBER = 13;
  public static final int EOF = 0;
  public static final int LOAD = 4;
  public static final int error = 1;
  public static final int REPEAT = 10;
  public static final int TERM = 2;
}

