
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 14 15:20:49 CET 2012
//----------------------------------------------------

package fr.uha.ensisa.compil.sound;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int TIMES = 13;
  public static final int IMPORT = 7;
  public static final int SEQUENCE = 11;
  public static final int EQUAL = 3;
  public static final int WITH_NOTES = 10;
  public static final int PLAY = 8;
  public static final int END = 14;
  public static final int VARIABLE = 18;
  public static final int NOTE = 17;
  public static final int PLAY_SIMULT = 9;
  public static final int STRING = 16;
  public static final int NUMBER = 15;
  public static final int EOF = 0;
  public static final int LOAD = 6;
  public static final int error = 1;
  public static final int NOTE_VELOCITY = 5;
  public static final int REPEAT = 12;
  public static final int TERM = 2;
  public static final int NOTE_DURATION = 4;
}

